import json

import pytest

from better_cov.reporter import (
    _color,
    _coverage_bar,
    _score_color,
    export_json,
    export_markdown,
    format_markdown_report,
    print_report,
)
from better_cov.scorer import FunctionScore, WeightedCoverageResult


def make_result(score: float = 0.75, functions: list[FunctionScore] | None = None) -> WeightedCoverageResult:
    return WeightedCoverageResult(
        global_score=score,
        global_score_pct=score * 100,
        raw_coverage=0.5,
        total_functions=len(functions or []),
        functions=functions or [],
        source_dirs=["src"],
        indicators=["import_count"],
    )


def make_function(
    file: str = "module.py",
    function: str = "run",
    line_rate: float = 1.0,
    importance: float = 0.5,
) -> FunctionScore:
    return FunctionScore(
        file=file,
        function=function,
        line_rate=line_rate,
        lines_covered=1,
        lines_total=1,
        importance=importance,
        weighted_contribution=line_rate * importance,
        indicator_scores={"import_count": importance},
    )


def test_report_helpers_cover_boundaries() -> None:
    """Verify report helpers render bars, ANSI text, and threshold colors at their boundaries."""
    assert _coverage_bar(0.0) == "[░░░░░░░░░░░░░░░░░░░░]"
    assert _coverage_bar(1.0) == "[████████████████████]"
    assert _color("text", "1") == "\033[1mtext\033[0m"
    assert _score_color(80) == "32"
    assert _score_color(50) == "33"
    assert _score_color(49.9) == "31"


def test_print_report_displays_empty_and_truncated_function_reports(capsys) -> None:
    """Verify console reports handle empty results and truncate long labels."""
    print_report(make_result(score=0.2), top_n=10)
    empty_output = capsys.readouterr().out
    assert "Indicators : import_count" in empty_output
    assert "Functions  : 0" in empty_output

    result = make_result(
        score=0.8,
        functions=[
            make_function(
                file="a-very-long-path/that-should-be-truncated/module.py",
                function="a_function_name_that_is_long_enough_to_be_truncated",
                line_rate=0.5,
            )
        ],
    )
    print_report(result, top_n=1)
    output = capsys.readouterr().out
    assert "Top 1 most important functions" in output
    assert "…" in output
    assert "50.0%" in output


@pytest.mark.parametrize(
    ("score", "badge"), [(0.8, "🟢"), (0.5, "🟡"), (0.4, "🔴")]
)
def test_format_markdown_report_uses_score_badges(score: float, badge: str) -> None:
    """Verify Markdown reports select badges at high, medium, and low thresholds."""
    result = make_result(
        score=score,
        functions=[
            make_function("a/" * 30 + "module.py", "run", 1.0),
            make_function("module.py", "partial", 0.6),
            make_function("module.py", "missing", 0.2),
        ],
    )

    markdown = format_markdown_report(result, top_n=3)

    assert "<!-- better-cov-report -->" in markdown
    assert f"{badge} Weighted score" in markdown
    assert "🟢 100.0%" in markdown
    assert "🟡 60.0%" in markdown
    assert "🔴 20.0%" in markdown
    assert "Indicators | import_count" in markdown
    assert "Generated by [better-cov]" in markdown


def test_format_markdown_report_handles_no_functions_and_top_n(capsys) -> None:
    """Verify Markdown and console reports handle empty results and zero requested rows."""
    result = make_result(score=0.5)
    markdown = format_markdown_report(result, top_n=0)
    assert "Functions | 0" in markdown
    assert "most important functions" not in markdown
    print_report(result, top_n=0)
    assert "Functions  : 0" in capsys.readouterr().out


def test_export_json_and_markdown_create_parent_directories(tmp_path) -> None:
    """Verify JSON and Markdown exports create parent directories and preserve report data."""
    function = make_function(line_rate=0.5, importance=0.75)
    function.indicator_scores = {"import_count": 0.75}
    result = make_result(score=0.75, functions=[function])
    json_path = tmp_path / "nested" / "report.json"
    markdown_path = tmp_path / "nested" / "report.md"

    export_json(result, json_path)
    export_markdown(result, markdown_path, top_n=1)

    data = json.loads(json_path.read_text(encoding="utf-8"))
    assert data["score"]["weighted_pct"] == 75.0
    assert data["score"]["raw_pct"] == 50.0
    assert data["config"]["total_functions"] == 1
    assert data["functions"][0]["function"] == "run"
    assert "## 📊 Weighted Coverage Report" in markdown_path.read_text(encoding="utf-8")
